name: Kolibrios gcc Installer

author: Egor00f

description: Install kolibrios gcc toolchain

branding:
  icon: 'download'
  color: 'gray-dark'

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install toolchain
      run: kolibrios-gcc-toolchain/./install
      shell: bash

    - name: add to path
      run: echo "/home/autobuild/tools/win32/bin" >> $GITHUB_PATH
      
