name: Kolibrios gcc Installer

author: Egor00f

description: Install kolibrios gcc toolchain

branding:
  icon: 'download'
  color: 'gray-dark'

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - if: runner.os == 'Windows'
      run: ${{ github.action_path }}\kolibrios-gcc-toolchain\install.bat
      shell: bash

    - if: runner.os == 'Linux'
      run: |
        sudo curl http://git.kolibrios.org/api/packages/Egor00f/debian/repository.key -o /etc/apt/keyrings/gitea-Egor00f.asc
        echo "deb [signed-by=/etc/apt/keyrings/gitea-Egor00f.asc] http://git.kolibrios.org/api/packages/Egor00f/debian bookworm main" | sudo tee -a /etc/apt/sources.list.d/gitea.list
        sudo apt update
        echo '/home/autobuild/tools' | sudo apt install kos32-gcc -y
      shell: bash

  
    - if: runner.os == 'Window'
      run: echo "C:\MinGW\msys\1.0\home\autobuild\tools\win32\bin" >> $GITHUB_PATH
      shell: bash

    - if: runner.os == 'Linux'
      run: echo "/home/autobuild/tools/win32/bin" >> $GITHUB_PATH
      shell: bash      
