name: Kolibrios gcc Installer

author: Egor00f

description: Install kolibrios gcc toolchain

branding:
  icon: 'download'
  color: 'gray-dark'

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install toolchain
      run: ${{ github.action_path }}/kolibrios-gcc-toolchain/./install
      shell: bash

