name: Kolibrios gcc Installer

author: Egor00f

description: Install kolibrios gcc toolchain

branding:
  icon: 'download'
  color: 'gray-dark'

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - if: runner.os == 'Windows'
      run: kolibrios-gcc-toolchain/./install.bat
      shell: bash

    - if: runner.os == 'Linux'
      run: echo '' | kolibrios-gcc-toolchain/./install
      shell: bash

    - name: add to path
      if: runner.os == "Window"
      run: echo "C:\MinGW\msys\1.0\home\autobuild\tools\win32\bin" >> $GITHUB_PATH
      elif: runner.os == "Linux"
      run: echo "/home/autobuild/tools/win32/bin" >> $GITHUB_PATH
      shell: bash      
