name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: egor00f/install-kolibrios-toolchain-action@main

      - name: Test toolchain working
        run: |
          /home/autobuild/tools/win32/bin/kos32-gcc -v
          /home/autobuild/tools/win32/bin/kos32-g++ -v
          /home/autobuild/tools/win32/bin/kos32-ar -V 
          /home/autobuild/tools/win32/bin/kos32-objcopy -V
          /home/autobuild/tools/win32/bin/kos32-strip -V
